spring:
  datasource:
    url: jdbc:mariadb://database-1.cv826wmq6eeu.ap-northeast-1.rds.amazonaws.com:3306/my_database
    username: admin
    password: my-secret-password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect